spring:
  application:
    name: fpd-order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://fpd.midavon.ru:5432/fpd?currentSchema=fpd_order}
    username: ${SPRING_DATASOURCE_USERNAME:fpd_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:fpd_admin}
    hikari:
      schema: fpd_order
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:fpd.midavon.ru:9092}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://fpd.midavon.ru:8443/realms/test"
          jwk-set-uri: "${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs"

kafka:
  order-service:
    group-id: ${KAFKA_ORDER_SERVICE_GROUP_ID:test}
    in-topic: ${KAFKA_ORDER_SERVICE_IN_TOPIC:courier_found_topic}
    out-topic: ${KAFKA_ORDER_SERVICE_OUT_TOPIC:courier_search_topic}

app:
  dictionary:
    url: ${APP_DICTIONARY_URL:localhost:8080}
    restaurant_url: "/restaurant"

yandex:
  api:
    key: ${YANDEX_API_KEY:c80bbf73-9f4a-4ac4-8f69-9b863ed3bb94}

server:
  port: 8080

jwt:
  auth:
    converter:
      principle-attribute: "preferred_username"